function fail {
  $1 "ERROR:" $2
  exit 1
}
